name: validate

on:
  pull_request:
    paths:
      - .github/workflows/validate.yaml
      - .github/renovate.*
      - default.json
      - package.json
      - pnpm-lock.yaml
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      - run: corepack enable pnpm
      - run: pnpm i
      - run: pnpm run test
